using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ACME.POC3.Migrations
{
    /// <inheritdoc />
    public partial class AddedInvoiceInvoiceLineMasterClient : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "AppInvoiceLines",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    InvoiceId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    ProductId = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    ProductName = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Quantity = table.Column<double>(type: "float", nullable: false),
                    Unit = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    UnitId = table.Column<int>(type: "int", nullable: false),
                    Price = table.Column<double>(type: "float", nullable: false),
                    DiscountRate = table.Column<double>(type: "float", nullable: false),
                    DiscountAmount = table.Column<double>(type: "float", nullable: false),
                    SubTotal = table.Column<double>(type: "float", nullable: false),
                    TotalWithDiscount = table.Column<double>(type: "float", nullable: false),
                    VatRate = table.Column<double>(type: "float", nullable: false),
                    VatAmount = table.Column<double>(type: "float", nullable: false),
                    TotalWithVat = table.Column<double>(type: "float", nullable: false),
                    TaxExcludingReason = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    TaxExcludingReasonCode = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    TaxExcludingReasonId = table.Column<int>(type: "int", nullable: false),
                    UnitCode = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    LineID = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ProductCode = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    MasterClientId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    TenantId = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    WithholdingTaxCode = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    WithholdingTaxRate = table.Column<double>(type: "float", nullable: false),
                    WithholdingTaxAmount = table.Column<double>(type: "float", nullable: false),
                    TotalAmount = table.Column<double>(type: "float", nullable: false),
                    ExportDeliveryCode = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ExportTransportModeCode = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ExportPackageNumber = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ExportPackageType = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ExportPackageQuantity = table.Column<double>(type: "float", nullable: false),
                    ExportPackageBrand = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ExportCustomsCode = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ExportShipmentNumber = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ExportShipmentGrossWeight = table.Column<double>(type: "float", nullable: false),
                    ExportShipmentNetWeight = table.Column<double>(type: "float", nullable: false),
                    ExportShipmentOriginCountryCode = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ExportShipmentCountryCode = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ExportShipmentCountryName = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ExportShipmentCityName = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ExportShipmentTownName = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ExportShipmentStreetName = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ExportShipmentBuildingName = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ExportShipmentBuildingNumber = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ExportShipmentPostalCode = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ProductTransactionId = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    ExtraProperties = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ConcurrencyStamp = table.Column<string>(type: "nvarchar(40)", maxLength: 40, nullable: true),
                    CreationTime = table.Column<DateTime>(type: "datetime2", nullable: false),
                    CreatorId = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    LastModificationTime = table.Column<DateTime>(type: "datetime2", nullable: true),
                    LastModifierId = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    IsDeleted = table.Column<bool>(type: "bit", nullable: false, defaultValue: false),
                    DeleterId = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    DeletionTime = table.Column<DateTime>(type: "datetime2", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_AppInvoiceLines", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "AppInvoices",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    Scenario = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    EInvoicePostCode = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    TesisatNo = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    SalesType = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    SalesTypeId = table.Column<int>(type: "int", nullable: true),
                    SendingType = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    WebUrl = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    SendingDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    ShippingPartyName = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ShippingVKN = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    PaymentDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    PaymentTypeCode = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    InvoiceType = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    InvoiceNumber = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    DocumentTrackNumber = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    TCKNVN = table.Column<string>(name: "TCKN_VN", type: "nvarchar(max)", nullable: false),
                    TaxOffice = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    TaxOfficeId = table.Column<int>(type: "int", nullable: false),
                    Country = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    CountryId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    City = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    CityId = table.Column<int>(type: "int", nullable: false),
                    Town = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    TownId = table.Column<int>(type: "int", nullable: false),
                    BuildingName = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    BuildingNumber = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    DoorNumber = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    PostCode = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    StreetName = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Email = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Phone = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Fax = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    WebAddress = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    InvoiceDate = table.Column<DateTime>(type: "datetime2", nullable: false),
                    SendDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    TemplateId = table.Column<int>(type: "int", nullable: false),
                    TemplateCode = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    OrderNumber = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    OrderDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    DispatchNumber = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    DispatchDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    ErpInvoiceNumber = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Note1 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    SubTotal = table.Column<double>(type: "float", nullable: false),
                    DiscountTotal = table.Column<double>(type: "float", nullable: false),
                    TotalWithDiscount = table.Column<double>(type: "float", nullable: false),
                    VatAmount = table.Column<double>(type: "float", nullable: false),
                    TotalWithVat = table.Column<double>(type: "float", nullable: false),
                    TotalWithholding = table.Column<double>(type: "float", nullable: false),
                    TotalAmount = table.Column<double>(type: "float", nullable: false),
                    SubTotalTL = table.Column<double>(type: "float", nullable: false),
                    DiscountTotalTL = table.Column<double>(type: "float", nullable: false),
                    TotalWithDiscountTL = table.Column<double>(type: "float", nullable: false),
                    VatAmountTL = table.Column<double>(type: "float", nullable: false),
                    TotalWithVatTL = table.Column<double>(type: "float", nullable: false),
                    TotalWithholdingTL = table.Column<double>(type: "float", nullable: false),
                    TotalAmountTL = table.Column<double>(type: "float", nullable: false),
                    ReturnInvoiceNumber = table.Column<double>(type: "float", nullable: false),
                    ReturnInvoiceId = table.Column<int>(type: "int", nullable: false),
                    CreatedBy = table.Column<int>(type: "int", nullable: false),
                    CurrencyId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    CurrencyCode = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Title = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Name = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Surname = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    CurrencyRate = table.Column<double>(type: "float", nullable: false),
                    SerialNumber = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    DrawInvoiceNumber = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    EnvelopeNumber = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    DrawEttn = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    Ettn = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    StatusId = table.Column<int>(type: "int", nullable: false),
                    StatusCode = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    StatusDescription = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ServiceResult = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ServiceResultDescription = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    EnvelopeId = table.Column<int>(type: "int", nullable: false),
                    TCKNVNSender = table.Column<string>(name: "TCKN_VN_Sender", type: "nvarchar(max)", nullable: false),
                    ReceiverPostBoxName = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    SenderPostBoxName = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ProfileId = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    UblText = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ChargeTotalAmount = table.Column<double>(type: "float", nullable: false),
                    PaymentDueDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    GIBDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    isEInvoice = table.Column<bool>(type: "bit", nullable: false),
                    isOutgoing = table.Column<bool>(type: "bit", nullable: false),
                    MasterClientId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    isDraft = table.Column<bool>(type: "bit", nullable: false),
                    isCancelled = table.Column<bool>(type: "bit", nullable: false),
                    cancelNote = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    cancelDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    isAccepted = table.Column<bool>(type: "bit", nullable: false),
                    acceptDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    isRejected = table.Column<bool>(type: "bit", nullable: false),
                    rejectNote = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    rejectDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    DirectionText = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    IntegrationDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    SourceId = table.Column<int>(type: "int", nullable: false),
                    SourceRefId = table.Column<int>(type: "int", nullable: false),
                    SourceRefGuid = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Vat0Matrah = table.Column<double>(type: "float", nullable: false),
                    Vat1Matrah = table.Column<double>(type: "float", nullable: false),
                    Vat8Matrah = table.Column<double>(type: "float", nullable: false),
                    Vat10Matrah = table.Column<double>(type: "float", nullable: false),
                    Vat18Matrah = table.Column<double>(type: "float", nullable: false),
                    Vat20Matrah = table.Column<double>(type: "float", nullable: false),
                    Vat26Matrah = table.Column<double>(type: "float", nullable: false),
                    Vat0Amount = table.Column<double>(type: "float", nullable: false),
                    Vat1Amount = table.Column<double>(type: "float", nullable: false),
                    Vat8Amount = table.Column<double>(type: "float", nullable: false),
                    Vat10Amount = table.Column<double>(type: "float", nullable: false),
                    Vat18Amount = table.Column<double>(type: "float", nullable: false),
                    Vat20Amount = table.Column<double>(type: "float", nullable: false),
                    Vat26Amount = table.Column<double>(type: "float", nullable: false),
                    Iban = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    SGKAccountingCost = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    SGKMukellefKodu = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    SGKMukellefAdi = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    SGKDosyaNo = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    SGKDonemStartDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    SGKDonemEndDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    TenantId = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    ProjectId = table.Column<int>(type: "int", nullable: false),
                    BuyerClientId = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    BuyerCustomerIdOrTaxNumber = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    BuyerTitle = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    BuyerAddress = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    BuyerCity = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    BuyerTown = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    BuyerCountry = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    BuyerEmail = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    PaymentMeansCode = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    PaymentMeansDescription = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    PaymentMeansIBAN = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    PaymentMeansCurrencyCode = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ExportDeliveryCode = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ExportTransportModeCode = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ExportFreightAmount = table.Column<double>(type: "float", nullable: false),
                    ExportInsuranceAmount = table.Column<double>(type: "float", nullable: false),
                    ExportShipmentNumber = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ExportShipmentCountryCode = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ExportShipmentCountryName = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ExportShipmentCityName = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ExportShipmentTownName = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ExportShipmentStreetName = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ExportShipmentBuildingName = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ExportShipmentBuildingNumber = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ExportShipmentPostalCode = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    TransactionId = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    isAffectStock = table.Column<bool>(type: "bit", nullable: false),
                    ExtraProperties = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ConcurrencyStamp = table.Column<string>(type: "nvarchar(40)", maxLength: 40, nullable: true),
                    CreationTime = table.Column<DateTime>(type: "datetime2", nullable: false),
                    CreatorId = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    LastModificationTime = table.Column<DateTime>(type: "datetime2", nullable: true),
                    LastModifierId = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    IsDeleted = table.Column<bool>(type: "bit", nullable: false, defaultValue: false),
                    DeleterId = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    DeletionTime = table.Column<DateTime>(type: "datetime2", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_AppInvoices", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "AppMasterClients",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    SourceId = table.Column<int>(type: "int", nullable: true),
                    SourceRefId = table.Column<int>(type: "int", nullable: true),
                    SourceRefGuid = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    TCKNVN = table.Column<string>(name: "TCKN_VN", type: "nvarchar(max)", nullable: false),
                    Title = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Title2 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Name = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Surname = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    TaxOffice = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    TaxOfficeId = table.Column<int>(type: "int", nullable: true),
                    Country = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    CountryId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    City = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    CityId = table.Column<int>(type: "int", nullable: true),
                    PriceListId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    CategoryId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    Town = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    TownId = table.Column<int>(type: "int", nullable: true),
                    ExchangeRateCalculation = table.Column<int>(type: "int", nullable: true),
                    BuildingName = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    BuildingNumber = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    DoorNumber = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    PostCode = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    StreetName = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Email = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Phone = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Fax = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    WebAddress = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Address = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    SourceCode = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    SourceLastUpdate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    TenantId = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    TotalCredit = table.Column<double>(type: "float", nullable: false),
                    TotalDebit = table.Column<double>(type: "float", nullable: false),
                    TotalBalance = table.Column<double>(type: "float", nullable: false),
                    TotalCreditLimit = table.Column<double>(type: "float", nullable: false),
                    TotalDebitLimit = table.Column<double>(type: "float", nullable: false),
                    TotalBalanceLimit = table.Column<double>(type: "float", nullable: false),
                    TotalCreditLimitUsed = table.Column<double>(type: "float", nullable: false),
                    TotalDebitLimitUsed = table.Column<double>(type: "float", nullable: false),
                    TotalBalanceLimitUsed = table.Column<double>(type: "float", nullable: false),
                    TotalCreditLimitLeft = table.Column<double>(type: "float", nullable: false),
                    TotalDebitLimitLeft = table.Column<double>(type: "float", nullable: false),
                    TotalBalanceLimitLeft = table.Column<double>(type: "float", nullable: false),
                    TotalCreditLimitLeftPercent = table.Column<double>(type: "float", nullable: false),
                    TotalDebitLimitLeftPercent = table.Column<double>(type: "float", nullable: false),
                    TotalBalanceLimitLeftPercent = table.Column<double>(type: "float", nullable: false),
                    ExtraProperties = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ConcurrencyStamp = table.Column<string>(type: "nvarchar(40)", maxLength: 40, nullable: true),
                    CreationTime = table.Column<DateTime>(type: "datetime2", nullable: false),
                    CreatorId = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    LastModificationTime = table.Column<DateTime>(type: "datetime2", nullable: true),
                    LastModifierId = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    IsDeleted = table.Column<bool>(type: "bit", nullable: false, defaultValue: false),
                    DeleterId = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    DeletionTime = table.Column<DateTime>(type: "datetime2", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_AppMasterClients", x => x.Id);
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "AppInvoiceLines");

            migrationBuilder.DropTable(
                name: "AppInvoices");

            migrationBuilder.DropTable(
                name: "AppMasterClients");
        }
    }
}
